### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by gjngeldenhuis**
A first pull request to start restructuring the documentation. This adds a direct link in the README file to the documentation which takes you to an index page. The next pull request will be to migrate wiki pages to the docs directory and structure the index a bit better as it gets more populated.

### CODE REVIEW

**Comment by smcclellan** [comment]
This looks great. Have you signed the [CLA](cla.puppetlabs.com)?

**Comment by gjngeldenhuis** [comment]
@smcclellan the CLA has been signed.

**Comment by gjngeldenhuis** [comment]
@smcclellan just a fyi, the CLA still refers to Dawn Foster who does not work at Puppet anymore so that might be worth getting changed.

**Comment by smcclellan** [comment]
@gjngeldenhuis Thanks for letting us know, it'll be fixed.

**Comment by smcclellan** [comment]
I've rebased, squashed the commits into one, and merged this PR.

**Pull request closed without merging**
