### PR TITLE
Positional arguments

### PR DESCRIPTION
**Pull request by smcclellan**
For use with a CLI, several commands will benefit from a specific ordering of positional arguments. This PR lays the groundwork for specifying the position of command arguments, then fits each command with positional indices for arguments where it makes sense. These will be included in the `schema` section of the API.

Example `GET /api/commands/delete-node`:
```
{
  "name": "delete-node",
  "help": {
    "summary": "Remove a single node from the database",
    "description": "Remove a single node from the database.  Should the node boot again it will be\nrediscovered and treated as any other new node.",
    "schema": "...omitted...",
    "examples": {
      "api": "Delete the node \"node17\":\n\n{\"name\": \"node17\"}",
      "cli": "Delete the node \"node17\":\n\nrazor delete-node --name node17"
    },
    "full": "...omitted..."
  },
  "schema": {
    "name": {
      "type": "string",
      "position": 0
    }
  }
}
```

Fixes https://tickets.puppetlabs.com/browse/RAZOR-673

### CODE REVIEW

**Comment by smcclellan** [comment]
Let's hold off on merging this until the client work is completed.

**Comment by smcclellan** [comment]
This is linked to https://github.com/puppetlabs/razor-client/pull/64.

**Comment by pcarlisle** [comment]
looks good to me

**Comment by steveax** [comment]
LGTM, @smcclellan, is there a merge order requirement for this and the client PR?

**Comment by smcclellan** [comment]
@steveax Doesn't really matter in this case. The change should be fully backward compatible anyway.

**Comment by smcclellan** [comment]
Rebased and merged.

**Pull request merged**
