### PR TITLE
Added Deployment Tools\amd64 to PSModulePATH to make sure we find the DI...

### PR DESCRIPTION
**Pull request by nickperry**
...SM powershell module

### CODE REVIEW

**Comment by nickperry** [comment]
With a fresh install of ADK 8.1, this path was not added to my PSModulePATH and therefore build-razor-winpe.ps1 could not find the DISM module.

**Comment by smcclellan** [comment]
Hi Nick, have you signed the [Puppet Labs CLA](https://cla.puppetlabs.com) yet?

**Comment by nickperry** [comment]
Hi. Yes, I signed it yesterday.

**Comment by smcclellan** [comment]
Rebased, revised commit message, and merged.

**Pull request closed without merging**
